import AppKit
import Observation
import os

/// One captured clipboard entry. In memory only — never written to disk.
///
/// `nonisolated`: this target sets `SWIFT_DEFAULT_ACTOR_ISOLATION = MainActor`,
/// so an unannotated type here would carry a main-actor-isolated `Equatable`
/// conformance that the pure, nonisolated de-duplication cannot use.
nonisolated struct ClipboardEntry: Identifiable, Equatable {

    enum Content: Equatable {
        case text(String)
        case image(Data)
    }

    let id = UUID()
    let content: Content
    let capturedAt: Date

    init(content: Content, capturedAt: Date = Date()) {
        self.content = content
        self.capturedAt = capturedAt
    }

    /// Equality ignores `id` and `capturedAt`: two entries are the same
    /// clipping if they hold the same bytes, which is what de-duplication
    /// needs when the user copies the same thing twice.
    static func == (lhs: Self, rhs: Self) -> Bool { lhs.content == rhs.content }
}

/// Clipboard history, capped and in memory.
///
/// **Nothing here touches disk.** The roadmap is blunt that this feature
/// stores everything the user copies and is the single thing most likely to
/// make a reviewer distrust a background agent. It is therefore off by
/// default, capped at ten entries, and lost on quit. Persisting it is a
/// separate decision nobody has made.
///
/// **Concealed items are never read, not merely never stored.** The type
/// check happens before any content is pulled off the pasteboard, so a
/// password manager's clipping is not momentarily held in this process.
///
/// **Hard rule 9, with one documented exception.** The timer stops when the
/// display sleeps and when the module is disabled. It deliberately does NOT
/// stop when the module is off screen: capture only-while-visible would
/// record nothing, since the point is to have a history ready by the time
/// you open the notch. The mitigations are that the poll is a single
/// integer read once a second, that it is off by default, and that both
/// other suspend paths are honoured.
@MainActor
@Observable
final class ClipboardService {

    @ObservationIgnored
    private static let logger = Logger(subsystem: "com.techie.PopNotch", category: "Clipboard")

    /// Ten is the roadmap's cap. A bigger history is a bigger pile of the
    /// user's secrets sitting in memory for no proportionate gain.
    @ObservationIgnored static let historyLimit = 10

    /// One second: `changeCount` is a single integer read, and anything
    /// slower feels like the notch missed a copy.
    @ObservationIgnored static let interval: TimeInterval = 1

    /// Markers the pasteboard community uses to say "do not record this".
    /// `ConcealedType` is what password managers set; the other two mark
    /// clippings written by tooling rather than by a person.
    @ObservationIgnored
    nonisolated static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    private(set) var entries: [ClipboardEntry] = []

    @ObservationIgnored private var timer: Timer?
    @ObservationIgnored private var displayAsleep = false
    @ObservationIgnored private var isEnabled = false
    /// Seeded from the current count so the clipping already sitting on the
    /// pasteboard at enable time is not swept up retroactively.
    @ObservationIgnored private var lastChangeCount = NSPasteboard.general.changeCount

    init() {
        let center = NSWorkspace.shared.notificationCenter
        center.addObserver(self, selector: #selector(displayDidSleep),
                           name: NSWorkspace.screensDidSleepNotification, object: nil)
        center.addObserver(self, selector: #selector(displayDidWake),
                           name: NSWorkspace.screensDidWakeNotification, object: nil)
    }

    deinit {
        timer?.invalidate()
        NSWorkspace.shared.notificationCenter.removeObserver(self)
    }

    // MARK: - Pure logic (testable without a pasteboard)

    /// Whether a clipping carrying these types may be recorded.
    ///
    /// Called *before* the content is read, which is the whole point.
    nonisolated static func shouldCapture(types: [String]) -> Bool {
        !types.contains { excludedTypes.contains($0) }
    }

    /// Newest first, de-duplicated, capped. Re-copying something already in
    /// the history moves it to the top rather than adding a duplicate.
    nonisolated static func inserting(_ entry: ClipboardEntry,
                                      into existing: [ClipboardEntry],
                                      limit: Int) -> [ClipboardEntry] {
        guard limit > 0 else { return [] }
        var result = existing.filter { $0 != entry }
        result.insert(entry, at: 0)
        if result.count > limit { result.removeLast(result.count - limit) }
        return result
    }

    /// One-line preview. Collapses whitespace so a copied code block does
    /// not render as a tall ragged block in a notch-sized row.
    nonisolated static func preview(of text: String, limit: Int = 48) -> String {
        let collapsed = text
            .replacingOccurrences(of: "\n", with: " ")
            .replacingOccurrences(of: "\t", with: " ")
            .split(separator: " ", omittingEmptySubsequences: true)
            .joined(separator: " ")
        guard collapsed.count > limit else { return collapsed }
        return String(collapsed.prefix(limit)) + "…"
    }

    // MARK: - Lifecycle

    func setEnabled(_ enabled: Bool) {
        guard enabled != isEnabled else { return }
        isEnabled = enabled
        Self.logger.notice("Clipboard history \(enabled ? "enabled" : "disabled", privacy: .public)")
        if !enabled {
            // Disabling is not just "stop looking": what was captured goes
            // too, so turning it off is a way to purge.
            entries.removeAll()
        }
        updateTimer()
    }

    private func updateTimer() {
        let shouldRun = isEnabled && !displayAsleep
        guard shouldRun != (timer != nil) else { return }
        if shouldRun {
            lastChangeCount = NSPasteboard.general.changeCount
            let timer = Timer.scheduledTimer(withTimeInterval: Self.interval, repeats: true) { _ in
                Task { @MainActor [weak self] in self?.poll() }
            }
            RunLoop.main.add(timer, forMode: .common)
            self.timer = timer
        } else {
            timer?.invalidate()
            timer = nil
        }
    }

    @objc private func displayDidSleep() {
        displayAsleep = true
        updateTimer()
    }

    @objc private func displayDidWake() {
        displayAsleep = false
        updateTimer()
    }

    // MARK: - Capture

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = (pasteboard.types ?? []).map(\.rawValue)
        guard Self.shouldCapture(types: types) else {
            // Count only. The whole point is that this content never leaves
            // the pasteboard, so it certainly never reaches the log.
            Self.logger.notice("Skipped a concealed or transient clipping")
            return
        }

        // Image first: a copied image often also offers a text type, and the
        // thumbnail is the more useful preview.
        if let image = pasteboard.data(forType: .tiff) ?? pasteboard.data(forType: .png) {
            record(.image(image))
        } else if let text = pasteboard.string(forType: .string),
                  !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            record(.text(text))
        }
    }

    private func record(_ content: ClipboardEntry.Content) {
        entries = Self.inserting(ClipboardEntry(content: content),
                                 into: entries, limit: Self.historyLimit)
        Self.logger.notice("Captured a clipping (\(self.entries.count, privacy: .public) held)")
    }

    // MARK: - Actions

    /// Puts an entry back on the pasteboard.
    func copyBack(_ entry: ClipboardEntry) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        switch entry.content {
        case .text(let text):
            pasteboard.setString(text, forType: .string)
        case .image(let data):
            pasteboard.setData(data, forType: .tiff)
        }
        // Our own write must not read back as a fresh capture.
        lastChangeCount = pasteboard.changeCount
        Self.logger.notice("Copied an entry back to the pasteboard")
    }

    func clear() {
        let count = entries.count
        entries.removeAll()
        Self.logger.notice("History cleared (\(count, privacy: .public) discarded)")
    }
}
