import XCTest
@testable import PopNotch

/// The privacy filter is the part that must never regress: a password
/// manager's clipping has to be rejected on its type, before any content is
/// read.
final class ClipboardPrivacyTests: XCTestCase {

    func testConcealedTypeIsRejected() {
        // What password managers set. This is the whole reason the filter
        // exists.
        XCTAssertFalse(ClipboardService.shouldCapture(
            types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]))
    }

    func testTransientAndAutoGeneratedAreRejected() {
        XCTAssertFalse(ClipboardService.shouldCapture(
            types: ["public.utf8-plain-text", "org.nspasteboard.TransientType"]))
        XCTAssertFalse(ClipboardService.shouldCapture(
            types: ["public.utf8-plain-text", "org.nspasteboard.AutoGeneratedType"]))
    }

    func testConcealedWinsRegardlessOfPosition() {
        // The marker may sit anywhere in the type list.
        XCTAssertFalse(ClipboardService.shouldCapture(
            types: ["org.nspasteboard.ConcealedType", "public.utf8-plain-text", "public.html"]))
    }

    func testOrdinaryClippingIsAccepted() {
        XCTAssertTrue(ClipboardService.shouldCapture(
            types: ["public.utf8-plain-text", "public.html"]))
        XCTAssertTrue(ClipboardService.shouldCapture(types: ["public.tiff"]))
    }

    func testEmptyTypeListIsAccepted() {
        // Nothing to exclude on; the caller still finds no content to store.
        XCTAssertTrue(ClipboardService.shouldCapture(types: []))
    }
}

/// History shape: newest first, de-duplicated, hard-capped.
final class ClipboardHistoryTests: XCTestCase {

    private func text(_ s: String) -> ClipboardEntry { .init(content: .text(s)) }

    func testNewestFirst() {
        var history: [ClipboardEntry] = []
        for word in ["one", "two", "three"] {
            history = ClipboardService.inserting(text(word), into: history, limit: 10)
        }
        XCTAssertEqual(history.map(\.content), [.text("three"), .text("two"), .text("one")])
    }

    func testCapDropsTheOldest() {
        var history: [ClipboardEntry] = []
        for i in 1...15 {
            history = ClipboardService.inserting(text("\(i)"), into: history, limit: 10)
        }
        XCTAssertEqual(history.count, ClipboardService.historyLimit)
        XCTAssertEqual(history.first?.content, .text("15"), "newest survives")
        XCTAssertEqual(history.last?.content, .text("6"), "oldest past the cap is dropped")
    }

    func testRecopyingMovesToTopWithoutDuplicating() {
        var history: [ClipboardEntry] = []
        for word in ["a", "b", "c"] {
            history = ClipboardService.inserting(text(word), into: history, limit: 10)
        }
        history = ClipboardService.inserting(text("a"), into: history, limit: 10)
        XCTAssertEqual(history.count, 3, "no duplicate row for the same clipping")
        XCTAssertEqual(history.first?.content, .text("a"))
    }

    func testImagesAndTextCoexist() {
        var history: [ClipboardEntry] = []
        history = ClipboardService.inserting(text("hello"), into: history, limit: 10)
        history = ClipboardService.inserting(.init(content: .image(Data([0x1, 0x2]))),
                                             into: history, limit: 10)
        XCTAssertEqual(history.count, 2)
        XCTAssertEqual(history.first?.content, .image(Data([0x1, 0x2])))
    }

    func testZeroLimitStoresNothing() {
        XCTAssertTrue(ClipboardService.inserting(text("x"), into: [], limit: 0).isEmpty)
    }
}

/// Previews go on a notch-sized row, so they must be one short line.
final class ClipboardPreviewTests: XCTestCase {

    func testShortTextIsUnchanged() {
        XCTAssertEqual(ClipboardService.preview(of: "hello"), "hello")
    }

    func testNewlinesAndTabsCollapse() {
        // A copied code block must not render as a tall ragged block.
        XCTAssertEqual(ClipboardService.preview(of: "let x = 1\n\tlet y = 2"),
                       "let x = 1 let y = 2")
    }

    func testLongTextIsTruncatedWithAnEllipsis() {
        let preview = ClipboardService.preview(of: String(repeating: "a", count: 200))
        XCTAssertEqual(preview.count, 49, "48 characters plus the ellipsis")
        XCTAssertTrue(preview.hasSuffix("…"))
    }

    func testRunsOfWhitespaceCollapseToSingleSpaces() {
        XCTAssertEqual(ClipboardService.preview(of: "a     b"), "a b")
    }
}

/// Off by default, and no timer left running behind a toggle.
@MainActor
final class ClipboardLifecycleTests: XCTestCase {

    func testStartsEmptyAndDisabled() {
        let service = ClipboardService()
        XCTAssertTrue(service.entries.isEmpty)
    }

    func testDisablingPurgesTheHistory() {
        // Turning it off is also how a user gets rid of what was captured.
        let service = ClipboardService()
        service.setEnabled(true)
        service.setEnabled(false)
        XCTAssertTrue(service.entries.isEmpty)
    }

    func testModuleIsOffByDefault() {
        let module = ClipboardModule(service: ClipboardService())
        XCTAssertFalse(module.isEnabled,
                       "recording everything a user copies is never opt-out")
    }

    func testModuleKeepsOutOfTheCollapsedRow() {
        let module = ClipboardModule(service: ClipboardService())
        XCTAssertFalse(module.wantsCompactDisplay)
    }

    func testClearEmptiesHistory() {
        let service = ClipboardService()
        service.clear()
        XCTAssertTrue(service.entries.isEmpty)
    }
}
